name: Eastern CRE Capital
favicon: null
layout_spectrum: 0.4101923245470971
typography_spectrum: 0.6979640028439462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1922807910013944
  lightness: 0.928325008135289
  saturation: 0.5580805062782019
  rhythmicContrast: 0.3467607570346445
purpose: []
