typography_spectrum: 0.6979640028439462
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1922807910013944
  lightness: 0.928325008135289
  saturation: 0.5580805062782019
  rhythmicContrast: 0.3467607570346445
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4101923245470971
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: EasternCRECapital
  email: nnn1031@gmail.com
  url: 'https://www.linkedin.com/in/nnn1031'
name: Eastern CRE Capital
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/71ecae17-58d9-4593-b65e-ccf9866b7c6c.jpg
title: New England Single Tenant Investors
content: []
purpose:
  - type: contact
    url: 'tel:6177449115'
    label: Call 6177449115
  - type: contact
    url: 'mailto:momara@atlanticretail.com'
    label: Contact me
description: Triple Net Lease Investments
github: true
url: 'http://www.easterncrecapital.com'
