layout_spectrum: 0.36292011489861153
typography_spectrum: 0.5311720188252518
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.215073291701403
  lightness: 0.45500588005150455
  saturation: 0.8107900590109317
  rhythmicContrast: 0.8034708463872718
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: EasternCRECapital
  email: nnn1031@gmail.com
  url: 'https://www.linkedin.com/in/nnn1031'
name: EasternCRECapital
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/71ecae17-58d9-4593-b65e-ccf9866b7c6c.jpg
title: New England Single Tenant Investors
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f39f4195-a394-416e-9f6d-c0727d0a9ee3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f39f4195-a394-416e-9f6d-c0727d0a9ee3.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: phone
    url: 'tel:6177749115'
    label: Call 6177749115
  - type: contact
    url: 'mailto:nnn1031@gmail.com'
    label: Contact Me
description: Focused on STNL Retail Properties in New England
github: true
url: 'http://www.easterncrecapital.com'
